Code review exercise
wolox-training/gm-code-review pull request #2
Opened 2019-04-16 21:10 UTC by icoluccio

2019-04-24 19:54 UTC, fedeest commented on Gemfile
> +  gem 'rubocop'
Agregá rubocop al group general, asi se puede corregir eso también.

2019-04-24 21:31 UTC, holywyvern commented on Gemfile
> +gem 'httparty'
Falta el bloquear la versión de las gemas, deberias agregar `'~> X.Y.Z'` donde X.Y.Z sea la version más reciente de la gema, para evitar conflictos a futuro.

Prioridad: **2**
Es un error muy comun, pero el gemfile.lock esta justamente para evitar esto en la mayoría de los casos

2019-04-24 21:31 UTC, holywyvern commented on Gemfile
> +  gem 'rubocop'
Lo mismo para rubocop.

2019-04-24 21:31 UTC, holywyvern commented on app/background/find_featured_posts.rb
> +      if likes.size >= 5
Yo esto lo prefiero como `post.update(featured: likes.size >= 5)`

Prioridad: **1**
No cambia la lógica, solo acorta la cantidad de codigo a interpetar.

2019-04-24 21:31 UTC, holywyvern commented on app/background/find_featured_posts.rb
> +    Post.all.each do |post|
Debería ser `Post.find_each`

Prioridad: **3**
No explota el sistema, porque esta en un worker, pero, estas revisando cientos de posts, no es tan bueno.

2019-04-24 21:31 UTC, holywyvern commented on app/background/update_like_count.rb
> +  def perform(post)
Debería pasar `post_id` en lugar de `post`.

Prioridad: **3**
Es un consumo de memoria y esfuerzo el serializar/deserializer un modelo.

2019-04-24 21:31 UTC, holywyvern commented on app/background/update_like_count.rb
> +    post.update(like_count: Like.where(post: post).count)
Deberias hacer `post.include(:likes).likes.count` para ahorrar idas a la base de datos.

Prioridad: **2**
De nuevo, es un tema de performance, no es algo que destruye el sistema.

2019-04-24 21:31 UTC, holywyvern commented on app/controllers/posts_controller.rb
> +    @posts = Post.all.order(created_at: :desc)
Hay una asignación que no sirve de nada.

Prioridad: **3**
Es malo porque da a confusion de si hace o no hace algo la variable de instancia.

2019-04-24 21:31 UTC, holywyvern commented on app/controllers/posts_controller.rb
> +    @posts = Post.all.order(created_at: :desc)
Si la idea es mostrar todos los posts en caso de no existir el usuario, falta un `render json: @posts`

Prioridad: **3**
El CR deberia de darse cuenta quizas de que esto es el problema.

2019-04-24 21:31 UTC, holywyvern commented on app/controllers/posts_controller.rb
> +      if User.exists? params[:user]
Podria resumirse como `user_param.present? && User.exists?(user_param)` y deberias de separar params[:user] como un metodo que lo consiga.

Prioridad: **2**
El codigo actual no me parece muy leible.

2019-04-24 21:31 UTC, holywyvern commented on app/controllers/posts_controller.rb
> +  def new
¿Es necesario este metodo?
No es una aplicación monolitica.

Prioridad: **1**
El metodo actual es inocuo, en este caso.

2019-04-24 21:31 UTC, holywyvern commented on app/controllers/posts_controller.rb
> +    @post = Post.find(params[:id])
Podria moverse el post a un metodo.

Prioridad: **3**
Es para evitar código repetido a futuro.

2019-04-24 21:31 UTC, holywyvern commented on app/controllers/posts_controller.rb
> +  def edit
En este caso, es lo mismo que el anterior.

¿Es necesario en una API?

Prioridad: **1**
El metodo actual no hace nada serio.

2019-04-24 21:31 UTC, holywyvern commented on app/controllers/posts_controller.rb
> +    @post = Post.new(post_params.merge(user: current_user))
Prefiero utilizar el "camino feliz" en un controller y hacer:

```rb
@post.create!(post_params.merge(user: current_user))
```
y agregar los rescue from de estos casos en api controller.

Pero puedo ser solo yo.

Prioridad: **4**
No hay seguridad que el post se guarde o no, eso tiene que saltar a la vista del CR.

2019-04-24 21:31 UTC, holywyvern commented on app/controllers/posts_controller.rb
> +    render :new
¿Esto funciona con APIs?

De nuevo, pensaba que era algo exclusivo de monoliticas.

2019-04-24 21:31 UTC, holywyvern commented on app/controllers/posts_controller.rb
> +    @post = Post.find(params[:id])
Por esto es que queria separarlo en un metodo como:

```rb
def post
  @post ||= Post.find(params[:id])
end
```

Prioridad: **3**
Me gustaría que el CR recalque que hay un poco de código repetido, aunque sea mínimo.

2019-04-24 21:31 UTC, holywyvern commented on app/controllers/posts_controller.rb
> +    if @post.update(post_params)
Yo ya dije, prefiero `@post.update!`

No obstante, si preferis hacer esto. head esta mal, deberia ser, `:created` y `:unprocessable_entity`

Prioridad: **4**
Minimo deberia detectar que los códigos de error estan mal.

2019-04-24 21:31 UTC, holywyvern commented on app/controllers/posts_controller.rb
> +    redirect_to posts_url, notice: 'Post was successfully destroyed.'
Lo mismo otra vez, prefiero el combo `@post.destroy! + rescue_from`

Y otra vez esta el redirect_to, que no sirve en apis, es algo de app monolitica.

Prioridad: **3**
No verifica que el post se haya realmente borrado.

2019-04-24 21:31 UTC, holywyvern commented on app/controllers/posts_controller.rb
> +    Like.create(post: post, user: current_user)
Aca hay un race condition,

Si bien es posible que no se ejecute el actualizador de likes primero, es posible que si lo haga con este código actual, aun con chances bajas.

Prioridad: **4**
Si no lo detectó antes, deberia detectar que esta pasando post en el worker, además del race condition.

2019-04-24 21:31 UTC, holywyvern commented on app/controllers/posts_controller.rb
> +    UpdateLikeCount.perform_async(post)
No estoy muy conforme con que el worker trabaje luego de que se hace un like.

Prioridad: **3**
No estoy seguro si tiene una buena explicación actualizarlo en un worker, es vestigio de algo viejo que quedo del CR anterior o esta bien esto.

2019-04-24 21:31 UTC, holywyvern commented on app/controllers/posts_controller.rb
> +    FindFeaturedPosts.perform_async
Esto es lo mismo, de, actualizar cada vez que se vea featured.
Deberia, o ser parte de la logica sincronica, o deberia haber un schedule corriendo periodicamente.

Prioridad: **3**
Algo tiene que mencionar de la lógica de negocio implementada, a mi me llama mucho la atención las deciciones de esto.

2019-04-24 21:31 UTC, holywyvern commented on app/controllers/repositories_controller.rb
> +class RepositoriesController < ApplicationController
Me gusto lo simple que se ve este controlador...
Nada, esta bien la integración con el servicio externo, solo lo queria decir.

2019-04-24 21:31 UTC, holywyvern commented on app/controllers/users_controller.rb
> +    @user = User.find(params[:id])
¿Esto es una app monolitica o no? Falta un render de json o esto va a una vista tradicional.

Prioridad: **4**
Esto lo tiene que al menos preguntar...

2019-04-24 21:31 UTC, holywyvern commented on app/controllers/users_controller.rb
> +    @user = User.find(params[:id])
Lo mismo acá...

2019-04-24 21:31 UTC, holywyvern commented on app/controllers/users_controller.rb
> +      render json: { errors: @user.errors.full_messages }, status: 422
Está al revés el resultado del if.

y 422 deberia ser cambiado por `:unprocessable_entity`

Prioridad: **4**
Es algo trivial, si, pero se tiene que notar.

2019-04-24 21:31 UTC, holywyvern commented on app/controllers/users_controller.rb
> +    user.update(twitter_id: params[:twitter_id], twitter_token: params[:twitter_token])
Acá debería notar de nuevo la falta de control del update.

Prioridad: **3**

2019-04-24 21:31 UTC, holywyvern commented on app/controllers/users_controller.rb
> +    user = User.find(params[:user_id])
¿Las acciones que no son index create show y demás usan user_id no?

2019-04-24 21:31 UTC, holywyvern commented on app/controllers/users_controller.rb
> +    render json: { timeline: Twitter.new(User.find(params[:id])).timeline }
Me estoy confundiendo y creo que Twitter es un modelo. O lo cambiaria a `Twitter.timeline(params[:user_id])` o a `TwitterApi.new(params[:user_id]).timeline`

Prioridad: **2**
Quizas `params[:id]` en lugar de `params[:user_id]` sea lo más grabe, el nombre es algo que me marea a mi.

2019-04-24 21:31 UTC, holywyvern commented on app/controllers/repositories_controller.rb
> +class RepositoriesController < ApplicationController
Por otro lado, no se si el servicio de Github usa metodos de clase o de instancia, si usa de instancia, a mi criterio me gusta.

2019-04-24 21:31 UTC, holywyvern commented on app/models/post.rb
> +  has_many :likes
Debería de marcarse lo de `dependant:`

Prioridad: **1**
Rubocop igual avisa, es un error trivial.

2019-04-24 21:31 UTC, holywyvern commented on app/models/user.rb
> +  has_many :posts
Lo mismo aca de los dependant

2019-04-24 21:31 UTC, holywyvern commented on app/models/user.rb
> +  validates :email, uniqueness: { case_sensitive: false }
estaría bueno validar el formato de email.

Prioridad: **2**
Si te conectas con un servicio federado, no es tan problema.

2019-04-24 21:31 UTC, holywyvern commented on app/third_party/github.rb
> +  BASE_URL = 'https://api.github.com'.freeze
yo preferiria hacer un:

```rb
module Github
  class << self
     include HTTParty
     base_url 'https://api.github.com'

     def repositories(username)
         get("/user/#{username}/repos").body
     end

     def gists(username)
        get("/user/#{username}/gists").body
     end
  end
end
```

Prioridad: **2**
Esto es mas un tema de estilos, puntos extra si recuerda lo de template strings, y aun mas si sugiere mover la url a secrets.

2019-04-24 21:31 UTC, holywyvern commented on app/third_party/twitter.rb
> +  URL = 'https://api.twitter.com/1.1'.freeze
Deberia sugerir moverlo a secrets, o al menos la version de la API.
Tambien deberias incluir el modulo HTTParty, me gusta más para agregar base_url y demás.

Prioridad: **3**
Deberia notar estas cosas.

2019-04-24 21:31 UTC, holywyvern commented on app/third_party/twitter.rb
> +    HTTParty.get(URL + '/statuses/user_timeline?user_id=' + user.twitter_id + '&token=' + @token).body
Deberias pasar query_id y token como query params de httparty.

`get(/statuses/user_timeline`, query: { user_id: user.twitter_id, token: token}).

Prioridad: **3**
Puede fallar por un tema de escape de caracteres de este modo.

2019-04-24 21:31 UTC, holywyvern commented on app/third_party/twitter.rb
> +    HTTParty.get(URL + '/statuses/user_timeline?user_id=' + user.twitter_id + '&token=' + @token).body
Deberias agregar los readers, o en su defecto usar variables de instancia: `attr_reader :user_id, :token`

Prioridad: **2**
Es mas que nada, un tema de mantener el codigo similar a través de toda la app

2019-04-24 21:31 UTC, holywyvern commented on app/third_party/weather_api.rb
> +  BASE = 'http://api.openweathermap.org/data/2.5'.freeze
Prefiero que se haga similar al código de Github.

Prioridad: **2**

2019-04-24 21:31 UTC, holywyvern commented on app/third_party/weather_api.rb
> +      BASE + "/weather?q=#{city}&appid=" + KEY + '&units=metric'
Deberia de avisar de usar query otra vez.

2019-04-24 21:31 UTC, holywyvern commented on config/routes.rb
> +  get 'repositories/github', to: 'repositories#github'
yo lo escribiría como:

```rb
resources :respositories, only: [] do
    collection do
        get :github
        get :github_gists
    end
end
```

Prioridad: **1**
Es algo que me gusta a mi de escribir las rutas así

2019-04-24 21:31 UTC, holywyvern commented on config/routes.rb
> +  resources :users, only: [:index, :show, :edit, :update] do
Acá podes decir %I[] pero no aporta mucho...

2019-04-24 21:31 UTC, holywyvern commented on db/migrate/20180313150206_devise_create_users.rb
> +    # add_index :users, :confirmation_token,   unique: true
Deberias utilizar los indices de confirmable para una mejor optimización.

Prioridad: *2*
Los indices son bastante importantes, aunque no rompan nada.

2019-04-24 21:31 UTC, holywyvern commented on spec/background/find_featured_posts_spec.rb
> +      expect(post.reload.featured).to be_truthy
¿ Deberia de notar que el post no le pasa esto porque no tiene 5 dias de antiguedad ?

2019-04-24 21:31 UTC, holywyvern commented on spec/background/find_featured_posts_spec.rb
> +      expect(post.reload.featured).to be_truthy
¿Deberia sugerir factory bot?

2019-04-24 21:31 UTC, holywyvern commented on spec/background/find_featured_posts_spec.rb
> +RSpec.describe FindFeaturedPosts do
No usamos `Rspec.describe` deberia ser solo describe

2019-04-24 21:31 UTC, holywyvern commented on spec/models/user_spec.rb
> +RSpec.describe User, type: :model do
`type:` es innecesario.

2019-04-24 21:33 UTC, holywyvern commented on Gemfile
> +  gem 'rubocop'
Corrige general, porque vos no haces `RAILS_ENV=production bundle exec rubocop spec app`
Que este solo en dev y testing hace que no se instale en produccion nada mas, no que no testee codigo que corre en produccion.

2019-04-25 13:02 UTC, fedeest requested changes

2019-04-25 13:02 UTC, fedeest commented on app/background/find_featured_posts.rb
> +    Post.all.each do |post|
Two things:

1. Use `find_each`

Gravity: 3

2. Do `Post.include(:likes)` so as not to a N+1 Query

Gravity: 5

2019-04-25 13:02 UTC, fedeest commented on app/controllers/posts_controller.rb
> +      if User.exists? params[:user]
Do this in one line

Gravity: 1

2019-04-25 13:02 UTC, fedeest commented on app/controllers/posts_controller.rb
> +    @post = Post.find(params[:id])
Use memoization here

2019-04-25 13:02 UTC, fedeest commented on app/controllers/posts_controller.rb
> +    @post = Post.find(params[:id])
Use memoization here

Gravity: 2

2019-04-25 13:02 UTC, fedeest commented on app/controllers/posts_controller.rb
> +    @post.save
Check for errors?

2019-04-25 13:02 UTC, fedeest commented on app/controllers/posts_controller.rb
> +      head :ok
JAJAJAJ this is too much

2019-04-25 13:02 UTC, fedeest commented on app/controllers/posts_controller.rb
> +    @post = Post.find(params[:id])
Use memoization here

2019-04-25 13:02 UTC, fedeest commented on app/background/find_featured_posts.rb
> +class FindFeaturedPosts
background? what is that.

This is a worker and should be in the worker folder and the class and file name should end with Worker too

Gravity: 5

2019-04-25 13:02 UTC, fedeest commented on app/background/update_like_count.rb
> +class UpdateLikeCount
same

2019-04-25 13:02 UTC, fedeest commented on app/background/update_like_count.rb
> +  def perform(post)
Don't pass an object to a worker, pass the object's ID

Gravity: 4

2019-04-25 13:02 UTC, fedeest commented on app/controllers/users_controller.rb
> +    @user = User.find(params[:id])
Use memoization

2019-04-25 13:02 UTC, fedeest commented on app/controllers/users_controller.rb
> +    @user = User.find(params[:id])
Use memoization

2019-04-25 13:02 UTC, fedeest commented on app/controllers/weather_controller.rb
> +      render json: { error: 'There was a problem' }, status: :bad_request
i18n

Gravity: 3 (depends on the project)

2019-04-25 13:02 UTC, fedeest commented on app/controllers/weather_controller.rb
> +    response = WeatherApi.new.temp(params[:city])
Why not a Service?

2019-04-25 13:02 UTC, fedeest commented on app/models/like.rb
> +  validates :post_id, uniqueness: { scope: %i[user_id] }
I'm pretty sure there's another way to do this validation a bit fancier

2019-04-25 13:02 UTC, fedeest commented on app/models/like.rb
> +  belongs_to :post, optional: false
Isn't it `optional: false` by default?

2019-04-25 13:02 UTC, fedeest commented on app/models/user.rb
> +         :recoverable, :rememberable, :trackable, :validatable
Does your devise configuration include all these?

2019-04-25 13:02 UTC, fedeest commented on config/routes.rb
> +  get 'weather/temperature', to: 'weather#temperature'
Why not resources?

2019-04-25 13:02 UTC, fedeest commented on spec/background/find_featured_posts_spec.rb
> +        Like.create(post: post, user: users[6])
Use factory bot

2019-04-25 13:02 UTC, fedeest commented on spec/models/user_spec.rb
> +      new_user = User.new(email: 'test@test.com', password: '123123123')
Use `let` for this

2019-04-25 18:23 UTC, holywyvern commented on app/models/like.rb
> +  belongs_to :post, optional: false
Depends on the rails version `optional: true < 5.3`  and `optional: false >= 5.3` There was a time than out boostrap used to require  `required: false` while our trainings use `optional: true`

2019-04-30 16:30 UTC, nicozar95 commented on Gemfile
> +gem 'devise'
lock version

2019-04-30 16:30 UTC, nicozar95 commented on Gemfile
> +gem 'jquery-rails'
lock version

2019-04-30 16:30 UTC, nicozar95 commented on Gemfile
> +gem 'sidekiq'
lock version

2026-04-13 21:08 UTC, closed without merging